name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and build binary
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
          pip install pyinstaller

      - name: Build Docker image
        run: |
          source venv/bin/activate
          pyinstaller -F hello_world.py
          IMAGE_NAME="cicd-101-workshop"
          TAG="0.1.${{ github.run_number }}"
          if [ -z "$DOCKER_LOGIN" ]; then
            FULL_IMAGE="${IMAGE_NAME}:${TAG}"
          else
            FULL_IMAGE="${DOCKER_LOGIN}/${IMAGE_NAME}:${TAG}"
          fi
          echo "Building Docker image: $FULL_IMAGE"
          docker build -t $FULL_IMAGE .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u $DOCKER_LOGIN --password-stdin

      - name: Push Docker image
        run: |
          IMAGE_NAME="cicd-101-workshop"
          TAG="0.1.${{ github.run_number }}"
          if [ -z "$DOCKER_LOGIN" ]; then
            FULL_IMAGE="${IMAGE_NAME}:${TAG}"
          else
            FULL_IMAGE="${DOCKER_LOGIN}/${IMAGE_NAME}:${TAG}"
          fi
          echo "Pushing Docker image: $FULL_IMAGE"
          docker push $FULL_IMAGE
